Vagrant.configure("2") do |config|
  # Specify the box URL
  config.vm.box = "debian/buster64"

  # Define the jumpbox machine
  config.vm.define "k8s-jumpbox" do |jumpbox|
    jumpbox.vm.provider "virtualbox" do |vb|
      vb.name = "jumpbox"
      vb.memory = 512
      vb.cpus = 1
      vb.customize ["createhd", "--filename", "z:/dev/vms/k8s-jumpbox1.vdi", "--size", 10240]
      vb.customize ["modifyvm", :id, "--vram", "32"]
    end
  end

  # Define k8sserver
  config.vm.define "k8sserver" do |k8sserver|
    k8sserver.vm.hostname = "k8sserver"
    k8sserver.vm.provider "virtualbox" do |vb|
      vb.name = "k8sserver"
      vb.memory = 2048
      vb.cpus = 1
      vb.customize ["createhd", "--filename", "z:/dev/vms/k8sserver.vdi", "--size", 20480]
      vb.customize ["modifyvm", :id, "--vram", "32"]
    end
  end

  # Define k8snode0 
  config.vm.define "k8snode0" do |k8snode0|
    k8snode0.vm.hostname = "k8snode0"
    k8snode0.vm.provider "virtualbox" do |vb|
      vb.name = "k8snode0"
      vb.memory = 2048
      vb.cpus = 1
      vb.customize ["createhd", "--filename", "z:/dev/vms/k8snode0.vdi", "--size", 20480]
      vb.customize ["modifyvm", :id, "--vram", "32"]
    end
  end

  # Define the k8snode1 machine
  config.vm.define "k8snode1" do |k8snode1|
    k8snode1.vm.hostname = "k8snode1"
    k8snode1.vm.provider "virtualbox" do |vb|
      vb.name = "node-1"
      vb.memory = 2048
      vb.cpus = 1
      vb.customize ["createhd", "--filename", "z:/dev/vms/k8snode1.vdi", "--size", 20480]
      vb.customize ["modifyvm", :id, "--vram", "32"]
    end
  end
end